version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecure
      MYSQL_DATABASE: feature_db
      MYSQL_USER: intuitive_user
      MYSQL_PASSWORD: supersecure

  src:
    build: .
    links:
      - db
    ports:
      - "7777:80"
    depends_on:
      - db
    volumes:
      - .:/opt/src

  web:
    build: ../front-end
    ports:
      - "80:80"
    volumes:
      - ../front-end:/opt/src/app
